"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-01 23:19:12.961445
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import bot.storage.types

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "arbitrage_opportunities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("route", sa.String(length=128), nullable=False),
        sa.Column("net_pct", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("size_quote", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("executed", sa.Boolean(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("timestamp", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("arbitrage_opportunities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_arbitrage_opportunities_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "balances_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("asset", sa.String(length=16), nullable=False),
        sa.Column("free", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("used", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("timestamp", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("balances_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_balances_snapshot_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "bot_state",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "equity_curve",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("equity", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("reserve", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("timestamp", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("equity_curve", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_equity_curve_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=64), nullable=True),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("amount", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("price", bot.storage.types.DecimalString(length=64), nullable=True),
        sa.Column("stop_price", bot.storage.types.DecimalString(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("filled", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("average_price", bot.storage.types.DecimalString(length=64), nullable=True),
        sa.Column("intent_id", sa.String(length=64), nullable=True),
        sa.Column("position_id", sa.String(length=64), nullable=True),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("created_at", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", bot.storage.types.UtcDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orders_client_order_id"), ["client_order_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_orders_exchange_order_id"), ["exchange_order_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_orders_position_id"), ["position_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_symbol"), ["symbol"], unique=False)

    op.create_table(
        "positions",
        sa.Column("position_id", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("amount", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("initial_amount", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("entry_price", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("initial_stop", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("stop_loss", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("stop_order_id", sa.String(length=64), nullable=True),
        sa.Column("take_profits", sa.JSON(), nullable=False),
        sa.Column("targets_hit", sa.Integer(), nullable=False),
        sa.Column("best_price", bot.storage.types.DecimalString(length=64), nullable=True),
        sa.Column("realized_pnl", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("fees", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("close_reason", sa.String(length=32), nullable=True),
        sa.Column("opened_at", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.Column("closed_at", bot.storage.types.UtcDateTime(timezone=True), nullable=True),
        sa.Column("bars_open", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("position_id"),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_positions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_positions_symbol"), ["symbol"], unique=False)

    op.create_table(
        "risk_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("timestamp", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risk_events_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_risk_events_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "signals",
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("score", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=True),
        sa.Column("timestamp", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trade_id", sa.String(length=64), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("price", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("amount", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("fee", bot.storage.types.DecimalString(length=64), nullable=False),
        sa.Column("fee_currency", sa.String(length=16), nullable=True),
        sa.Column("is_maker", sa.Boolean(), nullable=False),
        sa.Column("timestamp", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trades_client_order_id"), ["client_order_id"], unique=False
        )
        batch_op.create_index("ix_trades_exchange_trade", ["exchange", "trade_id"], unique=True)

    op.create_table(
        "risk_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("risk_score", sa.String(length=8), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", bot.storage.types.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_reports")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index("ix_trades_exchange_trade")
        batch_op.drop_index(batch_op.f("ix_trades_client_order_id"))

    op.drop_table("trades")
    op.drop_table("signals")
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_risk_events_code"))

    op.drop_table("risk_events")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_symbol"))
        batch_op.drop_index(batch_op.f("ix_positions_status"))

    op.drop_table("positions")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_symbol"))
        batch_op.drop_index(batch_op.f("ix_orders_status"))
        batch_op.drop_index(batch_op.f("ix_orders_position_id"))
        batch_op.drop_index(batch_op.f("ix_orders_exchange_order_id"))
        batch_op.drop_index(batch_op.f("ix_orders_client_order_id"))

    op.drop_table("orders")
    with op.batch_alter_table("equity_curve", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_equity_curve_timestamp"))

    op.drop_table("equity_curve")
    op.drop_table("bot_state")
    with op.batch_alter_table("balances_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_balances_snapshot_timestamp"))

    op.drop_table("balances_snapshot")
    with op.batch_alter_table("arbitrage_opportunities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_arbitrage_opportunities_timestamp"))

    op.drop_table("arbitrage_opportunities")
    # ### end Alembic commands ###
